name: dart_tensor_flow
description: A high-performance Tensor library for Dart, featuring AFT Transformers and MuZero implementations and other examples.
version: 1.0.0
repository: https://github.com/KellyKinyama/dart-tensor-flow

environment:
  sdk: ^3.11.0-296.4.beta

# Add regular dependencies here.
dependencies:
  bishop: ^1.4.4
  dartchess: ^0.12.0
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
